Maraton/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/urls.py
from django.urls import path

from apps.core.views.results import *
from apps.core.views.category import *
from apps.core.views.contact import *
from apps.core.views.extra_info import *
from apps.core.views.fotografia import *
from apps.core.views.index import IndexView
from apps.core.views.inscription import *
from apps.core.views.marabana import *
from apps.core.views.notice import *
from apps.core.views.rule import *
from apps.core.views.users import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # Marabana
    path('crear-info-marabana/', MarabanaCreate.as_view(), name='marabana-create'),
    path('eliminar-info-marabana/<int:pk>/', MarabanaDelete.as_view(), name='marabana-delete'),
    path('editar-info-marabana/<int:pk>/', MarabanaUpdate.as_view(), name='marabana-update'),
    # Extra Infor
    path('extra-info-list/', ExtraInformationList.as_view(), name='extra-info-list'),
    path('extra-info-create/', ExtraInformationCreate.as_view(), name='extra-info-create'),
    path('extra-info-update/<int:pk>/', ExtraInformationUpdate.as_view(), name='extra-info-update'),
    path('extra-info-delete/<int:pk>/', ExtraInformationDelete.as_view(), name='extra-info-delete'),
    # Rule
    path('rule-list/', RuleList.as_view(), name='rule-list'),
    path('rule-create/', RuleCreate.as_view(), name='rule-create'),
    path('rule-update/<int:pk>/', RuleUpdate.as_view(), name='rule-update'),
    path('rule-delete/<int:pk>/', RuleDelete.as_view(), name='rule-delete'),
    # Resultado
    path('result-list/', ResultList.as_view(), name='result-list'),
    path('result-create/', ResultCreate.as_view(), name='result-create'),
    path('result-update/<int:pk>/', ResultUpdate.as_view(), name='result-update'),
    path('result-delete/<int:pk>/', ResultDelete.as_view(), name='result-delete'),
    # Noticia
    path('notice-list/', NoticeList.as_view(), name='notice-list'),
    path('notice-create/', NoticeCreate.as_view(), name='notice-create'),
    path('notice-update/<int:pk>/', NoticeUpdate.as_view(), name='notice-update'),
    path('notice-delete/<int:pk>/', NoticeDelete.as_view(), name='notice-delete'),
    # Fotografiá
    path('fotografia-list/', FotografiaList.as_view(), name='fotografia-list'),
    path('fotografia-create/', FotografiaCreate.as_view(), name='fotografia-create'),
    path('fotografia-update/<int:pk>/', FotografiaUpdate.as_view(), name='fotografia-update'),
    path('fotografia-delete/<int:pk>/', FotografiaDelete.as_view(), name='fotografia-delete'),
    # Contacto
    path('contact-list/', ContactList.as_view(), name='contact-list'),
    path('contact-create/', ContactCreate.as_view(), name='contact-create'),
    path('contact-update/<int:pk>/', ContactUpdate.as_view(), name='contact-update'),
    path('contact-delete/<int:pk>/', ContactDelete.as_view(), name='contact-delete'),
    # Inscription
    path('inscription-list/', InscriptionList.as_view(), name='inscription-list'),
    path('inscription-create/', InscriptionCreate.as_view(), name='inscription-create'),
    path('inscription-delete/<int:pk>/', InscriptionDelete.as_view(), name='inscription-delete'),
    path('inscription-update/<int:pk>/', InscriptionUpdate.as_view(), name='inscription-update'),
    # Category
    path('category-list/', CategoryList.as_view(), name='category-list'),
    path('category-create/', CategoryCreate.as_view(), name='category-create'),
    path('category-delete/<int:pk>/', CategoryDelete.as_view(), name='category-delete'),
    path('category-update/<int:pk>/', CategoryUpdate.as_view(), name='category-update'),
    # User
    path('user-list/', ListarUsuario.as_view(), name='user-list'),
    path('user-create/', CrearUsuario.as_view(), name='user-create'),
    path('user-delete/<int:pk>/', EliminarUsuario.as_view(), name='user-delete'),
    path('user-update/<int:pk>/', EditarUsuario.as_view(), name='user-update'),
]

apps/core/models.py
import datetime

from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator, validate_integer
from django.db import models


class GeneralInformation(models.Model):
    datetime = models.DateTimeField('Fecha y hora')
    location = models.TextField('Lugar')
    description = models.TextField('Descripción')

    # banner (foto 16:9)

    def __str__(self):
        return 'Información general del Marabana'


class TitleTextBaseModel(models.Model):
    title = models.CharField('Título', max_length=100)
    text = models.TextField('Texto', null=True, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class ExtraInformation(TitleTextBaseModel):
    location = models.CharField('Ubicación', max_length=300)
    start_date = models.DateTimeField('Fecha inicio')
    end_date = models.DateTimeField('Fecha fin')
    photo = models.ImageField('Foto', upload_to='images/', null=True, blank=True)


class Category(TitleTextBaseModel):
    pass


class Rule(TitleTextBaseModel):
    pass


categories = (
    ('m', 'Maratón'),
    ('mm', 'Media Maratón'),
    ('10', '10 km'),
    ('msr', 'Maratón silla de ruedas'),
    ('mmsr', 'Medio Maratón silla de ruedas'),
    ('10sr', '10 km silla de ruedas'),
)


class Result(models.Model):
    name = models.CharField('Nombre', max_length=100)
    last_name = models.CharField('Apellidos', max_length=200)
    country = models.CharField('País', max_length=100)
    gender = models.SmallIntegerField('Género', choices=(
        (0, 'M'),
        (1, 'F')
    ))
    email = models.EmailField('Correo')
    duration = models.PositiveIntegerField('Duración en minutos')
    date = models.DateField('Fecha de de la carrera', default=datetime.datetime.utcnow())
    category = models.CharField('Categoría', max_length=10, choices=categories)

    def __str__(self):
        return f'Resultado de carrera de {self.name} {self.last_name}'


class Inscription(models.Model):
    name = models.CharField('Nombre', max_length=100)
    last_name = models.CharField('Apellidos', max_length=200)
    address = models.TextField('Dirección')
    country = models.CharField('País', max_length=100)
    postal_code = models.CharField('Código postal', max_length=5, validators=[MinLengthValidator(5), validate_integer])
    dni = models.CharField('Carnet de id', max_length=11, validators=[MinLengthValidator(11), validate_integer])
    birth_date = models.DateField('Fecha de nacimiento')
    gender = models.SmallIntegerField('Género', choices=(
        (0, 'Masculino'),
        (1, 'Femenino')
    ))
    phone = models.CharField('Teléfono', max_length=8, validators=[MinLengthValidator(8), validate_integer])
    email = models.EmailField('Correo')
    email_confirm = models.EmailField('Confirmación de correo')
    average_time = models.PositiveSmallIntegerField('Tiempo estimado', choices=(
        (1, 'Menos de 3h'),
        (2, 'Entre 3h y 3h15'),
        (3, 'Entre 3h15 y 3h30'),
        (4, 'Entre 3h30 y 3h45'),
        (5, 'Entre 3h45 y 4h'),
        (6, 'Más de 4h'),
    ))
    race_rules = models.BooleanField('Reglamento de la carrera', default=False)
    is_active = models.BooleanField('Aprobada', default=False)

    def clean(self):
        if self.email != self.email_confirm:
            raise ValidationError({'email_confirm': 'Los correos no coinciden.'})
        if self.race_rules is False:
            raise ValidationError({'race_rules': 'Debe estar de acuerdo con el reglamento de la carrera.'})
        return super().clean()

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save()

    def __str__(self):
        return f'Inscripción de {self.name} {self.last_name}'


class Fotografia(models.Model):
    image = models.ImageField('Imagen', upload_to='images/')

    def __str__(self):
        return self.image.name


class Notice(TitleTextBaseModel):
    date = models.DateTimeField('Fecha')
    image = models.ImageField('Imagen', upload_to='images/')


class Contact(models.Model):
    type = models.CharField('Tipo de contacto', max_length=120)
    name = models.CharField('Nombre', max_length=120)
    address = models.TextField('Dirección')
    phone = models.CharField('Teléfono', max_length=8, validators=[validate_integer])
    email = models.EmailField('Correo')
    web = models.URLField('Sitio Web')

apps/core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class MyUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

apps/core/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return

apps/core/views/campeonato.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from apps.core.models import Campeonato


class CampeonatoCreate(LoginRequiredMixin, generic.CreateView):
    model = Campeonato
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('champion-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Crear Campeonato'
        context['back_url'] = self.success_url
        context['is_create'] = True
        return context


class CampeonatoUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Campeonato
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('champion-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = f'Actualizar Campeonato: {self.get_object()}'
        context['back_url'] = self.success_url
        return context


class CampeonatoList(LoginRequiredMixin, generic.ListView):
    model = Campeonato
    template_name = 'title_text_base/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.GET.get('search'):
            return qs.filter(title__icontains=self.request.GET.get('search'))
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Listado de Campeonatos'
        context['add_url'] = reverse_lazy('champion-create')
        context['update_url'] = '/champion-update/'
        context['delete_url'] = '/champion-delete/'
        return context


class CampeonatoDelete(LoginRequiredMixin, generic.DeleteView):
    model = Campeonato
    template_name = 'pages/delete.html'
    success_url = reverse_lazy('champion-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['model_name'] = 'Campeonato'
        context['back_url'] = self.success_url
        return context

apps/core/views/category.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from apps.core.models import Category


class CategoryCreate(LoginRequiredMixin, generic.CreateView):
    model = Category
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('category-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Crear Categoría'
        context['back_url'] = self.success_url
        context['is_create'] = True
        return context


class CategoryUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Category
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('category-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = f'Actualizar Categoría: {self.get_object()}'
        context['back_url'] = self.success_url
        return context


class CategoryList(LoginRequiredMixin, generic.ListView):
    model = Category
    template_name = 'title_text_base/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.GET.get('search'):
            return qs.filter(title__icontains=self.request.GET.get('search'))
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Listado de Categorías'
        context['add_url'] = reverse_lazy('category-create')
        context['update_url'] = '/category-update/'
        context['delete_url'] = '/category-delete/'
        return context


class CategoryDelete(LoginRequiredMixin, generic.DeleteView):
    model = Category
    template_name = 'pages/delete.html'
    success_url = reverse_lazy('category-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['model_name'] = 'Categoría'
        context['back_url'] = self.success_url
        return context

apps/core/views/contact.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from apps.core.models import Contact


class ContactCreate(LoginRequiredMixin, generic.CreateView):
    model = Contact
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('contact-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Crear Contacto'
        context['back_url'] = self.success_url
        context['is_create'] = True
        return context


class ContactUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Contact
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('contact-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = f'Actualizar Contacto: {self.get_object()}'
        context['back_url'] = self.success_url
        return context


class ContactList(generic.ListView):
    model = Contact
    template_name = 'contact/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.GET.get('search'):
            return qs.filter(title__icontains=self.request.GET.get('search'))
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Listado de Contactos'
        context['add_url'] = reverse_lazy('contact-create')
        context['update_url'] = '/contact-update/'
        context['delete_url'] = '/contact-delete/'
        return context


class ContactDelete(LoginRequiredMixin, generic.DeleteView):
    model = Contact
    template_name = 'pages/delete.html'
    success_url = reverse_lazy('contact-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['model_name'] = 'Contacto'
        context['back_url'] = self.success_url
        return context

apps/core/views/extra_info.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from apps.core.models import ExtraInformation


class ExtraInformationCreate(LoginRequiredMixin, generic.CreateView):
    model = ExtraInformation
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('extra-info-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Crear Información Extra'
        context['back_url'] = self.success_url
        context['is_create'] = True
        return context


class ExtraInformationUpdate(LoginRequiredMixin, generic.UpdateView):
    model = ExtraInformation
    template_name = 'pages/create-update.html'
    success_url = reverse_lazy('extra-info-list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['text'] = f'Actualizar Información Extra: {self.get_object()}'
        context['back_url'] = self.success_url
        return context


class ExtraInformationList(LoginRequiredMixin, generic.ListView):
    model = ExtraInformation
    # template_name = 'pages/table-list.html'
    template_name = 'extra_info/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.GET.get('search'):
            return qs.filter(title__icontains=self.request.GET.get('search'))
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['text'] = 'Listado de Informaciones Extras'
        context['add_url'] = reverse_lazy('extra-info-create')
        return context


class ExtraInformationDelete(LoginRequiredMixin, generic.DeleteView):
    model = ExtraInformation
    template_name = 'pages/delete.html'
    success_url = reverse_lazy('extra-info-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['model_name'] = 'Información Extra'
        context['back_url'] = self.success_url
        return context

apps/core/templates/inscription/activate.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% block main %}
    {% block carousel %}

    {% endblock %}
    <section class="section-delete">
        <div class="container">
            <div>
                <h3>Aprobar {{ model_name }}!</h3>
            </div>
            <br>
            <form action="" method="post">
                {% csrf_token %}
                <div class="alert alert-dismissible alert-success">
                    <h4 class="alert-heading">Aprobar!</h4>
                    <p class="mb-0 fs-6">Estás seguro que desea aprobar <b>{{ object }}?</b></p>
                </div>
                {{ form.is_active|attr:'checked:true'|add_class:'d-none' }}
                <div class="text-center">
                    <a href="{{ back_url }}" class="btn btn-outline-secondary btn-lg">Atrás</a>
                    <button type="submit" class="btn btn-primary btn-lg">Aprobar</button>
                </div>
            </form>
            <br>
        </div>
    </section>
{% endblock %}

apps/core/templates/inscription/create.html
{% extends 'main.html' %}
{% block main %}
    {% block carousel %}

    {% endblock %}
    {% load widget_tweaks %}
    <section class="section-create-update">
        <div class="container-lg">
            <div>
                <h3>{{ text }}</h3>
            </div>
            <br>
            <div class="card">
                <div class="card-body">
                    {% if form.errors %}
                        <div class="alert alert-dismissible alert-danger">
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            <h4>Por favor corrige los errores en el formulario.</h4>
                        </div>
                    {% endif %}


                    <form action="" method="post" novalidate enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.name.id }}"
                                           class="form-label mt-4">{{ form.name.label }}</label>
                                    {{ form.name|add_class:'form-control' }}
                                    {% if form.name.errors %}
                                        <small class="text-danger">{{ form.name.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.last_name.id }}"
                                           class="form-label mt-4">{{ form.last_name.label }}</label>
                                    {{ form.last_name|add_class:'form-control' }}
                                    {% if form.last_name.errors %}
                                        <small class="text-danger">{{ form.last_name.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="{{ form.address.id }}"
                                           class="form-label mt-4">{{ form.address.label }}</label>
                                    {{ form.address|add_class:'form-control'|attr:'rows:3' }}
                                    {% if form.address.errors %}
                                        <small class="text-danger">{{ form.address.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.country.id }}"
                                           class="form-label mt-4">{{ form.country.label }}</label>
                                    {{ form.country|add_class:'form-control' }}
                                    {% if form.country.errors %}
                                        <small class="text-danger">{{ form.country.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.postal_code.id }}"
                                           class="form-label mt-4">{{ form.postal_code.label }}</label>
                                    {{ form.postal_code|add_class:'form-control' }}
                                    {% if form.postal_code.errors %}
                                        <small class="text-danger">{{ form.postal_code.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.dni.id }}"
                                           class="form-label mt-4">{{ form.dni.label }}</label>
                                    {{ form.dni|add_class:'form-control'|attr:'type:number' }}
                                    {% if form.dni.errors %}
                                        <small class="text-danger">{{ form.dni.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.birth_date.id }}"
                                           class="form-label mt-4">{{ form.birth_date.label }}</label>
                                    {{ form.birth_date|add_class:'form-control'|attr:'type:date' }}
                                    {% if form.birth_date.errors %}
                                        <small class="text-danger">{{ form.birth_date.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.gender.id }}"
                                           class="form-label mt-4">{{ form.gender.label }}</label>
                                    {{ form.gender|add_class:'form-control' }}
                                    {% if form.gender.errors %}
                                        <small class="text-danger">{{ form.gender.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.phone.id }}"
                                           class="form-label mt-4">{{ form.phone.label }}</label>
                                    {{ form.phone|add_class:'form-control'|attr:'type:number' }}
                                    {% if form.phone.errors %}
                                        <small class="text-danger">{{ form.phone.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.email.id }}"
                                           class="form-label mt-4">{{ form.email.label }}</label>
                                    {{ form.email|add_class:'form-control'|attr:'type:email' }}
                                    {% if form.email.errors %}
                                        <small class="text-danger">{{ form.email.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.email_confirm.id }}"
                                           class="form-label mt-4">{{ form.email_confirm.label }}</label>
                                    {{ form.email_confirm|add_class:'form-control'|attr:'type:email' }}
                                    {% if form.email_confirm.errors %}
                                        <small class="text-danger">{{ form.email_confirm.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label for="{{ form.average_time.id }}"
                                           class="form-label mt-4">{{ form.average_time.label }}</label>
                                    {{ form.average_time|add_class:'form-control' }}
                                    {% if form.average_time.errors %}
                                        <small class="text-danger">{{ form.average_time.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12 col-md-6 d-flex flex-column justify-content-end">
                                <div class="form-group ">
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" role="switch"
                                               id="{{ form.race_rules.id }}" name="race_rules">
                                        <label class="form-check-label" for="{{ form.race_rules.id }}">Acepto los
                                            términos del reglamento de la carrera.</label>
                                    </div>
                                    {% if form.race_rules.errors %}
                                        <small class="text-danger">{{ form.race_rules.errors }}</small>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <br>
                        <div class="text-center">
                            <a href="{{ back_url }}" class="btn btn-lg btn-outline-secondary">Atrás</a>
                            <button type="submit" class="btn btn-lg btn-primary">Enviar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

apps/core/templates/inscription/list.html
{% extends 'components/table-list.html' %}

{% block search %}
    <form action="">
        <div class="input-group mb-3">
            <input type="search" name="search" list="datalistOptions" class="form-control"
                   placeholder="Buscar por nombre">
            <datalist id="datalistOptions">
                {% for object in object_list %}
                    <option value="{{ object.name }}">
                {% endfor %}
            </datalist>
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
        </div>
    </form>
{% endblock %}

{% block thead %}
    <th>Nombre</th>
    <th>Teléfono</th>
    <th>Carnet ID</th>
    <th>Correo</th>
    <th>Tiempo de carrera</th>
    <th>Estado</th>
    <th>Opciones</th>
{% endblock %}

{% block tbody %}
    {% for object in object_list %}
        <tr class="">
            <td>{{ object.name }} {{ object.last_name }}</td>
            <td>+53 {{ object.phone }}</td>
            <td>{{ object.dni }}</td>
            <td>{{ object.email }}</td>
            <td>{{ object.get_average_time_display }}</td>
            <td class="text-center">{% if object.is_active %}
                <i class="bx bx-check-circle fs-3 text-success"></i>{% else %}
                <i class="bx bxs-x-circle fs-3 text-danger"></i>{% endif %}</td>
            <td>
{#                <a href="{{ result_create }}{{ object.pk }}" class="btn btn-outline-primary">Resultado</a>#}
                <a href="{{ update_url }}{{ object.pk }}" class="btn btn-outline-success" title="Aprobar"><i
                    class="bx bx-check-circle"></i></a>
                <a href="{{ delete_url }}{{ object.pk }}" class="btn btn-outline-danger" title="Eliminar"><i
                        class="bx bx-trash"></i></a>
            </td>
        </tr>
    {% endfor %}

{% endblock %}